kernel:
  image: linuxkit/kernel:4.19.56
  cmdline: "console=tty0 console=tty1 console=ttyS0"
init:
  - linuxkit/init:1d8e0532ca588c5ad0d9ca6038349a70bb7ac626
  - linuxkit/runc:c1f0db27e71d948f3134b31ce76276f843849b0a
  - linuxkit/containerd:751de142273e1b5d2d247d2832d654ab92e907bc
  - linuxkit/ca-certificates:v0.7
  - linuxkit/memlogd:v0.7
onboot:
  - name: sysctl
    image: linuxkit/sysctl:v0.7
    readonly: false
    binds:
      - /etc/sysctl.d/01-kubernetes.conf:/etc/sysctl.d/01-kubernetes.conf
  - name: sysfs
    image: linuxkit/sysfs:v0.7
  - name: rngd1
    image: linuxkit/rngd:v0.7
    command: ["/sbin/rngd", "-1"]
  - name: dhcpcd1
    image: linuxkit/dhcpcd:v0.7
    command: ["/sbin/dhcpcd", "--nobackground", "--env", "force_hostname=YES", "-f", "/dhcpcd.conf", "-1"]
  - name: format
    image: linuxkit/format:v0.7
    command: ["/usr/bin/format", "-type", "xfs", "-label", "NODE", "-verbose"]
  - name: mounts
    image: linuxkit/mount:v0.7
    command: ["/usr/bin/mountie", "-label", "NODE", "/var/node"]
services:
  - name: rngd
    image: linuxkit/rngd:v0.7
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.7
  - name: acpid
    image: linuxkit/acpid:v0.7
    cgroupsPath: systemreserved/acpid
  - name: ntpd
    image: linuxkit/openntpd:v0.7
    cgroupsPath: systemreserved/ntpd
  - name: getty
    image: linuxkit/getty:v0.7
    # env:
    #  - INSECURE=true
    cgroupsPath: systemreserved/getty
  - name: logwrite
    image: linuxkit/logwrite:v0.7
    cgroupsPath: systemreserved/logwrite
  - name: kmsg
    image: linuxkit/kmsg:v0.7
    cgroupsPath: systemreserved/kmsg
  - name: sshd
    image: linuxkit/sshd:v0.7
    binds:
    - /root/.ssh/authorized_keys:/root/.ssh/authorized_keys
    - /etc/resolv.conf:/etc/resolv.conf
    - /run:/run
    - /tmp:/tmp
    - /etc:/hostroot/etc
    - /usr/bin/ctr:/usr/bin/ctr
    - /usr/bin/runc:/usr/bin/runc
    - /containers:/containers
    - /var/log:/var/log
    - /var/node:/var/node
    - /var/lib/containerd:/var/lib/containerd
    - /dev:/dev
    - /sys:/sys

    # SHARED NODE PATHS
    - /var/node/root:/root # /root
    cgroupsPath: systemreserved/sshd

  # Start K8s stuff
  - name: containerd
    image: docker.pkg.github.com/rmb938/linuxkit-pkg-containerd/containerd:1.0.0-amd64
    cgroupsPath: podruntime/cri-containerd
  - name: kubelet
    image: docker.pkg.github.com/rmb938/linuxkit-pkg-kubelet/kubelet:1.0.1-amd64
    cgroupsPath: podruntime/kubelet
  - name: kubeadm
    image: docker.pkg.github.com/rmb938/linuxkit-pkg-kubelet/kubelet:1.0.1-amd64
    cgroupsPath: podruntime/kubeadm
    command: ["/usr/local/bin/kubeadm.sh"]
files:
  - path: /root/.ssh/authorized_keys
    source: .ssh/id_rsa.pub
    mode: "0600"
    optional: true
  - path: /etc/os-release
    contents: |
      PRETTY_NAME="LinuxKit Kubernetes Project"
  - path: /etc/sysctl.d/01-kubernetes.conf
    source: files/etc/sysctl.d/01-kubernetes.conf
trust:
  org:
    - linuxkit
