version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01 
    steps:
      - run:
          name: Install Docker
          command: |
            sudo apt-get update
            sudo apt install docker
            sudo systemctl start docker
      - run:
          name: Install LinuxKit
          command: |
            wget https://dl.google.com/go/go1.12.9.linux-amd64.tar.gz
            tar -xvf go1.12.7.linux-amd64.tar.gz
            sudo mv go /usr/local
            go get -u github.com/linuxkit/linuxkit/src/cmd/linuxkit
            sudo mv ~/go/bin/linuxkit /usr/local/bin
