version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01 
    steps:
      - run:
          name: Install Docker
          command: |
            sudo apt-get update
            sudo apt install docker
            sudo systemctl start docker
      - run:
          name: Install LinuxKit
          command: |
            go get -u github.com/linuxkit/linuxkit/src/cmd/linuxkit
            sudo mv ~/go/bin/linuxkit /usr/local/bin
