org: rbelgrave
image: kubelet
network: true
arches:
  - amd64
config:
  binds:
  - /dev:/dev
  - /etc/resolv.conf:/etc/resolv.conf:ro
  - /etc/os-release:/etc/os-release:ro
  - /var/log:/host/var/log

  # SHARE NODE PATHS START
  - /run/node:/run:rshared,rbind # run
  - /var/node/var:/var:rshared,rbind # var

  - /var/node/etc/kubernetes:/etc/kubernetes:rshared,rbind # /etc/kubernetes
  - /var/node/etc/cni/net.d:/etc/cni/net.d:rshared,rbind # /etc/cni/net.d
  - /var/node/opt/cni/bin:/opt/cni/bin:rshared,rbind # /opt/cni/bin
  mounts:
  - type: bind
    source: /sys/fs/cgroup
    destination: /sys/fs/cgroup
    options: ["rw","rbind","rshared","nosuid","noexec","nodev","relatime"]
  capabilities:
  - all
  rootfsPropagation: shared
  pid: host
  runtime:
    cgroups:
      - systemreserved
      - podruntime
      - kubepods
    mkdir:
      - /run/node
      - /var/node/var
      - /var/node/var/lib/kubelet
      - /var/node/etc/kubernetes
      - /var/node/etc/cni/net.d
      - /var/node/opt/cni/bin
